# define docker compose file version
version: '3.7'

#define services that will be used
services:
  # service 1 with name item-app
  item-app:
    # use image from docker hub wisuprawida with tag v1
    image: wisnuprawida/item-app:v1
    # always restart if the container is dead because server restart, etc
    restart: always
    # port 80 in the host will be bind with port 8080 in the container
    ports:
      - 8000:8080
    # wait for item-db to start before starting this service
    depends_on:
      - item-db
  # service 2 with name item-db
  item-db:
    # use mongo image with tag 3
    image: mongo:3
    # always restart if the container is dead because server restart, etc
    restart: always
    # use volumes with name app-db to store data
    volumes:
      - app-db:/data/db

# volumes definition
volumes:
  app-db: